"""help

Revision ID: 1cf48a9ba09e
Revises: 
Create Date: 2023-08-17 14:17:16.551333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf48a9ba09e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('member', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cat_cults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motto', sa.String(), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('cult_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], name=op.f('fk_cat_cults_cat_id_cats')),
    sa.ForeignKeyConstraint(['cult_id'], ['cults.id'], name=op.f('fk_cat_cults_cult_id_cults')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('co_mingle', sa.Boolean(), nullable=True),
    sa.Column('catcult_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catcult_id'], ['cat_cults.id'], name=op.f('fk_events_catcult_id_cat_cults')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('cat_cults')
    op.drop_table('cults')
    op.drop_table('cats')
    # ### end Alembic commands ###
