"""event posting

Revision ID: adc7caae2742
Revises: fcd7722bc8dc
Create Date: 2023-08-22 09:49:53.581661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc7caae2742'
down_revision = 'fcd7722bc8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cult_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_events_catcult_id_cat_cults', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_events_cult_id_cults'), 'cults', ['cult_id'], ['id'])
        batch_op.drop_column('catcult_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catcult_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_events_cult_id_cults'), type_='foreignkey')
        batch_op.create_foreign_key('fk_events_catcult_id_cat_cults', 'cat_cults', ['catcult_id'], ['id'])
        batch_op.drop_column('cult_id')

    # ### end Alembic commands ###
