"""reseeding

Revision ID: fcd7722bc8dc
Revises: 1cf48a9ba09e
Create Date: 2023-08-18 13:55:30.911140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd7722bc8dc'
down_revision = '1cf48a9ba09e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat_cults', schema=None) as batch_op:
        batch_op.drop_column('motto')

    with op.batch_alter_table('cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('member')

    with op.batch_alter_table('cults', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motto', sa.String(), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('cults', schema=None) as batch_op:
        batch_op.drop_column('motto')

    with op.batch_alter_table('cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('picture')

    with op.batch_alter_table('cat_cults', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motto', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
